// AUTO-GENERATED by train_models.py from NSL-KDD-like data
// EDGE_LOOKUP[srcBytes_bin][serrorRate_bin]
// 0=Normal 1=DoS 2=Probe 3=R2L 4=U2R
#ifndef EDGE_LOOKUP_H
#define EDGE_LOOKUP_H

static const int EDGE_LOOKUP[10][10] = {
    { 0, 0, 2, 2, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=0
    { 3, 3, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=1
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=2
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=3
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=4
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=5
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=6
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=7
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=8
    { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 },  // srcBytes_bin=9
};

#endif